describe('login test practice', () => {
it('Verify Login with given positive and negative', () => {
cy.visit('https://practicetestautomation.com/practice-test-login/')
cy.get('input[name="username"]').type("student")
cy.get('input[name="password"]').type("Password123")
cy.get('button[class="btn"]').click()
cy.url().should('include',"https://practicetestautomation.com/logged-in-successfully/")
cy.get('strong').should('have.text','Congratulations student. You successfully logged in!')
cy.get('a[class="wp-block-button__link has-text-color has-background has-very-dark-gray-background-color"]').should('be.visible').click()
cy.get('input[name="username"]').type("incorrectUser")
cy.get('input[name="password"]').type("Password123")
cy.get('button[class="btn"]').click()
cy.get('.show').should('be.visible').and('have.text','Your username is invalid!')
cy.get('input[name="username"]').type("student")
cy.get('input[name="password"]').type("incorrectPassword")
cy.get('button[class="btn"]').click()
cy.get('.show').should('be.visible').and('have.text','Your password is invalid!')
})
})